services:
  frontend:
    build: ./FRONT_END
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3001

  backend:
    build: ./BACK_END
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_NAME=student_management

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: student_management
    ports:
      - "3307:3306"
